Fix colorized output while building
reference bash instead instead of sh
Some systems symlink sh to bash while others symlink to dash or use sh
on it's own

Change-Id: Iaa87d001d1a174b0220085816ea5b3f28a7ab34a

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Super-mega opticharger of doom
 # Shrinks apks by running pngcrush or optipng or pngout on png images
@@ -39,14 +39,14 @@ then
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo $CL_RED"Set APKCERTS to the path to your apkcerts.txt file"$CL_RST
+        echo -e $CL_RED"Set APKCERTS to the path to your apkcerts.txt file"$CL_RST
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo $CL_RED"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$CL_RST
+    echo -e $CL_RED"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$CL_RST
 fi
 
 if [ "$(which pngcrush)" != "" ];
@@ -71,26 +71,26 @@ then
         pngout $1
     }
 else
-    echo $CL_RED"Please install pngcrush, optipng, or pngout"$CL_RST
+    echo -e $CL_RED"Please install pngcrush, optipng, or pngout"$CL_RST
     exit 1;
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo $CL_RED"Please ensure aapt is in your \$PATH"$CL_RST
+    echo -e $CL_RED"Please ensure aapt is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo $CL_RED"Please ensure zipalign is in your \$PATH"$CL_RST
+    echo -e $CL_RED"Please ensure zipalign is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo $CL_CYN"Optimizing"$CL_RST" $NAME...";
+    echo -e $CL_CYN"Optimizing"$CL_RST" $NAME...";
 
     if [ "$2" != "" ];
     then
@@ -98,32 +98,32 @@ then
         KEY=build/target/product/security/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo $CL_RED"$CERT does not exist!";$CL_RST
+            echo -e $CL_RED"$CERT does not exist!";$CL_RST
             exit 1;
         fi
     else
         APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
-        [ $QUIET ] || echo "APKINFO: $APKINFO";
+        [ $QUIET ] || echo -e "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo $CL_RED"No apk info for $NAME";$CL_RST
+            echo -e $CL_RED"No apk info for $NAME";$CL_RST
             exit 1;
         fi
-        CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
-        KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
+        CERT=`echo -e $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
+        KEY=`echo -e $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo $CL_RED"Unable to find certificate for $NAME"$CL_RST
+            echo -e $CL_RED"Unable to find certificate for $NAME"$CL_RST
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo $CL_GRN"$NAME is presigned, skipping"$CL_RST
+            echo -e $CL_GRN"$NAME is presigned, skipping"$CL_RST
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo $CL_YLW"Certificate:"$CL_RST" $CERT";
+    [ $QUIET ] || echo -e $CL_YLW"Certificate:"$CL_RST" $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
@@ -132,19 +132,19 @@ then
     unzip -q $BASE/$1
     for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
     do
-        [ $QUIET ] || echo $CL_GRN"Crushing $x"$CL_RST
+        [ $QUIET ] || echo -e $CL_GRN"Crushing $x"$CL_RST
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo $CL_GRN"Repacking apk.."$CL_RST
+    [ $QUIET ] || echo -e $CL_GRN"Repacking apk.."$CL_RST
     aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
 
-    [ $QUIET ] || echo $CL_YLW"Resigning with cert: `echo $CERT`"$CL_RST
+    [ $QUIET ] || echo -e $CL_YLW"Resigning with cert: `echo -e $CERT`"$CL_RST
 
-    [ $QUIET ] || echo java -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
+    [ $QUIET ] || echo -e java -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
     java -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    [ $QUIET ] || echo $CL_GRN"Zipalign.."$CL_RST
+    [ $QUIET ] || echo -e $CL_GRN"Zipalign.."$CL_RST
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
@@ -152,5 +152,5 @@ then
     fi
     rm $BASE/$1.old
 else
-    echo "Usage: $0 [apk file]"
+    echo -e "Usage: $0 [apk file]"
 fi
